pull-request
corecodeio/entry-challenge-v1 pull request #1
Opened 2020-06-13 05:52 UTC by JeffLopez502

2020-06-16 02:36 UTC, Ktoxcon reviewed
Buen comienzo.

Resuelve los siguientes comentarios.

2020-06-16 02:36 UTC, Ktoxcon commented on src/client.ts
> +// Estoy utilizando FETCH API y Promises (promesas)
El código debe poder expresarse así mismo, por lo que los
comentarios no son necesarios.

2020-06-16 02:36 UTC, Ktoxcon commented on src/client.ts
> +let challengeUserData = {
Por favor, coloca este bloque en un .src/data.json e importalo para reducir el tamaño de este file y mejorar la organización.

2020-06-16 02:36 UTC, Ktoxcon commented on src/client.ts
> +		password: '  ',
Busca una manera de agregar la contraseña sin ponerla directamente en el código (hardcoded).

2020-06-16 02:36 UTC, Ktoxcon commented on src/client.ts
> +    	],
Es útil que instales un prettier en tu editor,
Prueba esta extensión : https://github.com/prettier/prettier-vscode

2020-06-16 02:36 UTC, Ktoxcon commented on src/client.ts
> +
Encapsula tus peticiones fetch en funciones asíncronas.

2020-06-16 02:36 UTC, Ktoxcon commented on src/client.ts
> +}).then( resp => resp.json() )
Como buena práctica de ES8 utiliza bloques try catch con async, await.

2020-06-16 04:30 UTC, netpoe requested changes
@JeffLopez502 vas por buen camino. 
por favor resuelve los comentarios. 

Gracias @Ktoxcon 


cc @sofiacastillo

2020-06-17 03:44 UTC, netpoe commented on src/client.ts
> +}).then( resp => resp.json() )
@Ktoxcon procura utilizar `markdown de código` cuando utilices keywords.

2020-06-18 06:53 UTC, JeffLopez502 commented on src/client.ts
> +
Hola, soy nuevo en las funciones asincronas, estaba intentando con esto 

async function upData() {

	try {		
		const getPass = await fetch( 'http://95.217.235.69/jeffabl502@gmail.com', {
			method: 'GET',
			headers: {
				"Content-Type": "application/json",
				"x-password": ""
			}
		})
		const resPass = await getPass.json()
		console.log( resPass );
	} catch ( error ) {
		console.log( error );
	}
}

Sin embargo no logro hacerlo funcionar, podrias indicarme que ¿estoy haciendo mal?
Agradezco tu respuesta

2020-06-18 17:31 UTC, Ktoxcon commented on src/client.ts
> +
Que tal @JeffLopez502 espero esto sea de ayuda

Cada función asíncrona retorna un `Promise`Object . Un `await` statement opera en una promesa, esperando hasta que esta se resuelva o sea rechazada.

Por ello no puedes hacer un `console.log()` al resultado de una función asíncrona directamente, para obtener el resultado de tu función asíncrona debes resolver la `Promise` ya se con `.then()` o `await`. El `.then()` method resuelve y pone a tu disposición el resultado de la `Promise`.

Simplificando, no puedes acceder al resultado de una `Promise` desde fuera de la `Promise`, es parte del modelo de trabajo con `Promises`

Adicionalmente Estos enlaces te pueden ser de ayuda:
[Async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)
[Await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await)

2020-06-18 19:17 UTC, netpoe commented on src/client.ts
> +
Buena explicación @Ktoxcon 
Gracias

2020-06-18 20:08 UTC, Ktoxcon commented on src/client.ts
> +
Gracias @netpoe

2025-02-15 02:46 UTC, closed without merging