pugaIsaias@parangaricutirimicuaro | Creating Pull Request
corecodeio/entry-challenge-v1 pull request #12
Opened 2020-06-18 22:42 UTC by pugaIsaias

- First time using typescript, and first time doing a pull request on Github.
- Tried to use express, just to find out its a listener. And not a package to do commands.
- Used fetch to do both the POST and GET.
- Read the code on Index.ts to find out the JSON path. And retrieve the claveDeAcceso with GET.
- Package.json may be be able to reduce since I don't use most of the imports.

2020-06-19 01:59 UTC, MConcoba commented
@pugaIsaias Buen comienzo,
Soluciona los siguientes comments

2020-06-19 02:08 UTC, MConcoba commented on src/client.js
> +});
En las instrucciones pide crear un archivo `client.ts`, este archivo no es necesario, recuerda que estamos trabajando con `TypeScript`

2020-06-19 02:13 UTC, MConcoba commented on src/data.json
> +}
Modifica este archivo a `data.ts`

2020-06-19 02:16 UTC, MConcoba commented on src/data.json
> +    },
Ingresar una contraseña directamente en el código, es una mala practica de seguridad, hay que buscar una manera para no introducirla de manera directa!

2020-06-19 02:19 UTC, MConcoba commented on src/data.json
> +            },
Debes de completar todas las preguntas, te falta esta....

2020-06-19 02:24 UTC, MConcoba commented on src/client.ts
> +console.log(email); // output 'testing'
El uso de `variables globales `en JS, no es una buena practica lo mejor es declararlas en `el scope de la función donde se van a utilizar` o en este caso como es una `variable de entorno` puedes simplemente usarla dentro de tu función donde la necesites.

2020-06-19 02:25 UTC, MConcoba commented on src/client.ts
> +.catch((err) => {console.log('ERROR: ', err.message)}); // need catch or it won't work
Algo que no es obligatorio, pero da buena estética al código es agregar una linea en blanco al final de los archivos de código, te recomiendo que lo hagas!

2020-06-19 03:25 UTC, netpoe commented on src/data.json
> +}
@MConcoba hay que ser más claros con esta instrucción: 

> Cambia el nombre de este archivo de `data.json` a `data.ts`

2020-06-19 04:35 UTC, MConcoba commented on src/data.json
> +}
@netpoe ok, entendido

2020-06-19 07:50 UTC, pugaIsaias commented on src/client.js
> +});
Muy bien ya elimine los archivo `.js` que se crean cuando le doy `tsc client.ts ` en la consola.

2020-06-19 07:54 UTC, pugaIsaias commented
- Se elimina archivos `.js`
- `data.json `ahora es `data.ts`
- se utiliza `.env` para manejar el password
- se agrega solucion a pregunta de linea de codigo de la definicion de React.useEffect
- Se agrego linea vacia al final de los archivo `.ts`

2020-06-19 07:55 UTC, pugaIsaias commented on src/client.ts
> +.catch((err) => {console.log('ERROR: ', err.message)}); // need catch or it won't work
OK lo voy a tomar en cuenta.

2020-06-19 07:58 UTC, pugaIsaias commented on src/client.ts
> +console.log(email); // output 'testing'
`const url `se movio dentro de cada una de las funciones.

Pregunta: los `import` tambien se hacen a nivel de funcion o estos estan bien a nivel global?

2020-06-19 07:59 UTC, pugaIsaias commented on src/data.json
> +            },
Listo

2020-06-19 08:01 UTC, pugaIsaias commented on src/client.js
> +});
Ya elimine todos los `.js `que se crearon cuando corria `tsc client.ts` en mi terminal.

2020-06-19 08:03 UTC, pugaIsaias commented on src/data.json
> +}
LIsto

2020-06-19 08:06 UTC, pugaIsaias commented on src/data.json
> +    },
Listo, y utilize el `.env` para manejar la contraseña.

2020-06-19 20:56 UTC, MConcoba commented on src/client.ts
> +console.log(email); // output 'testing'
No los `import`, estan bien a nivel global

2020-06-19 21:18 UTC, MConcoba commented on src/client.ts
> +        console.log(json.bienvenido.claveDeAcceso);
Hay que procurar no dejar `console.logs.`
Vamos a aprender a utilizar herramientas de debugging para no utilizar `console.logs`

2020-06-19 21:18 UTC, MConcoba commented on src/client.ts
> +        console.log(json.bienvenido.claveDeAcceso);
Hay que procurar no dejar `console.logs.`
Vamos a aprender a utilizar herramientas de debugging para no utilizar `console.logs`

2020-06-19 21:23 UTC, MConcoba commented on src/client.ts
> +    //optional paramethers
Procura no utilizar `comentarios`, ya que el codigo se tiene que explicar por si mismo

2020-06-19 22:22 UTC, pugaIsaias commented on src/client.ts
> +        console.log(json.bienvenido.claveDeAcceso);
Ok, pero por el momento. Solo elimino los `console.log`?

2020-06-19 22:28 UTC, pugaIsaias commented on src/client.ts
> +    //optional paramethers
Y elimino `comentarios`

2020-06-19 23:33 UTC, netpoe requested changes
@pugaIsaias resuelve los comentarios. 

También, `package-lock.json` no es necesario, para esto estamos usando `yarn` y `yarn` crea su propio `yarn.lock`. 

Igualmente, por favor instala https://github.com/prettier/prettier-vscode en tu editor y agrega estas líneas en tu `settings.json`: 

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
```

2020-06-19 23:33 UTC, netpoe commented on src/client.ts
> +    if (response.ok) {
Estos bloques de `if, else` no son necesarios. Para eso existe el `try/catch` 
Remuévelos por favor.

2020-06-19 23:33 UTC, netpoe commented on src/client.ts
> +    if (response.ok) {
Igualmente, estos bloques no son necesarios.

2020-06-19 23:33 UTC, netpoe commented on src/data.ts
> +export { data };
```suggestion
export default data;
```

2020-06-19 23:33 UTC, netpoe commented on src/data.ts
> +const data ={
```suggestion
export const data = {
```

2020-06-19 23:33 UTC, netpoe commented on src/data.ts
> +        "password": process.env.API_KEY
Este sería un nombre más adecuado: 

```suggestion
        "password": process.env.PASSWORD
```

2020-06-19 23:35 UTC, pugaIsaias commented
- Se elimina `console.log`. Ya que se depurara de otra forma.

- Se elimina los comentarios. Ya que se debe a dar a enteder si ellos.

- Adicionalmente elimine algunas Dependencias de cosas que ya no utilize (express, body-parser, axios) del `package.json. ` Sin consecuencias al resultado.

- Y intento agregar 2 espacios al final del codigo. A ver como lo recibe GitHub.

2020-06-19 23:35 UTC, MConcoba commented on src/client.ts
> +
Los bloque de` if, else` que tines, no son necesarios, podrias eliminarlos

2020-06-19 23:39 UTC, MConcoba commented on package-lock.json
> +{
este file no debería estar en este PR. No hay necesidad de modificar el package.json. Además estamos usando yarn y éste genera yarn.lock.

2020-06-19 23:40 UTC, MConcoba commented
@pugaIsaias  puedes instalar la extensión `prettier `en tu editor.

También puedes agregar esto a tus settings.json:

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
```

2020-06-20 01:23 UTC, pugaIsaias commented on src/client.ts
> +    if (response.ok) {
@netpoe  Muy bien ,muchas gracias. Con eso ya puedo quitar el `.catch `que tenia que utilizar al llamar las funciones.

2020-06-20 01:24 UTC, pugaIsaias commented on src/data.ts
> +const data ={
Muy bien ya realize este cambio. Y elimine el export que realizaba al final para evitar redundancia.

2020-06-20 01:27 UTC, pugaIsaias commented on src/data.ts
> +        "password": process.env.API_KEY
Muy bien ya corregí el nombre de la variable.

2020-06-20 01:27 UTC, pugaIsaias commented on src/client.ts
> +
LIsto

2020-06-20 01:28 UTC, pugaIsaias commented on package-lock.json
> +{
LIsto eliminado.

2020-06-20 01:30 UTC, pugaIsaias commented on src/data.ts
> +export { data };
Elimine por completo esta linea. Ya que la exportaba directamente en la siguiente corrección.

2020-06-20 02:56 UTC, pugaIsaias reviewed
Cambio hechos. Favor revisar cualquier otro cambio que se necesite.

2020-06-20 03:20 UTC, netpoe requested changes
@pugaIsaias muy cerca. 
por favor instala `prettier` y al hacer save de tus files deberías ver cómo se alinea tu código.

2020-06-22 03:49 UTC, netpoe reviewed
👍 

@pugaIsaias buen trabajo. 

Revisa tu correo con las invitaciones a Slack y Github.

2020-07-12 08:34 UTC, closed without merging