GitHub rvelasquezc/entry challenge
corecodeio/entry-challenge-v1 pull request #19
Opened 2020-06-25 00:31 UTC by rvelasquezc

pull request

2020-06-25 04:34 UTC, netpoe reviewed
@rvelasquezc gracias por tu propuesta. 

@blindlp va a revisar tu código y de ser aprobado, te avisaremos por este medio.

2020-06-26 02:44 UTC, blindlp reviewed
evitar colocar hard-Code axios.get(`${process.env.BASE_URL}:rvelasquezumg@gmail.com`, {

2020-06-26 02:47 UTC, blindlp commented
Excelente inicio @rvelasquezc,  puedes instalar prettier? y activar este setting  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },

adicionalmente puedes revisar la respuesta de tu función NetInfo()

2020-06-26 02:49 UTC, blindlp requested changes
evita colocar código hard-code axios.get(`${process.env.BASE_URL}:rvelasquezumg@gmail.com`, {

2020-06-26 04:26 UTC, netpoe commented
> Excelente inicio @rvelasquezc, puedes instalar prettier? y activar este setting "editor.codeActionsOnSave": {
> "source.organizeImports": true
> },
> 
> adicionalmente puedes revisar la respuesta de tu función getInfo()

@blindlp 
Debes poner más detalle a tus comentarios. 

Utiliza bloques de código cuando sea necesario: 

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true
}
```

o cuando hables de conceptos de software: `prettier`.

2020-06-26 04:29 UTC, netpoe requested changes
@rvelasquezc estás muy cerca. Resuelve los comentarios.

2020-06-26 04:29 UTC, netpoe commented on .env
> +Mail = rvelasquezumg@gmail.com
la nomenclatura convencional para variables de ambiente es: `EN_MAYUSCULAS`.

2020-06-26 04:29 UTC, netpoe commented on .vscode/settings.json
> +}
Este directorio `.vscode` no debe estar en este PR. Quítalo por favor.

2020-06-26 04:29 UTC, netpoe commented on .env
> +Access_key = e110b57447492
Tu contraseña sigue pública aunque esté en las variables de ambiente. 

NUNCA subas este file: `.env` a un repositorio, ni público, ni privado.

2020-06-26 04:33 UTC, rvelasquezc commented on .env
> +Mail = rvelasquezumg@gmail.com
Gracias hare los cambio y detallare en descripción para que sea mas comprensible

2020-06-26 05:50 UTC, closed without merging