Challenge solved
corecodeio/entry-challenge-v1 pull request #3
Opened 2020-06-13 20:55 UTC by Ktoxcon

2020-06-14 00:40 UTC, netpoe requested changes
Buen comienzo. 

Por favor, resuelve los comentarios.

2020-06-14 00:40 UTC, netpoe commented on src/client.ts
> +              "x-password": "qvfWwe3"
Muy buen trabajo, pero aquí enseñaste tu contraseña. 
Cómo podemos hacer para mantener la seguridad de tu sistema?

2020-06-14 00:40 UTC, netpoe commented on src/client.ts
> +                answer: "Respuesta: If I were a senior developer I would like to build something that helps improve everyone's learning in the technological field",
Interesante. Por ejemplo?
Algún caso de uso concreto?

2020-06-14 00:40 UTC, netpoe commented on src/client.ts
> +                answer: "Respuesta:https://github.com/facebook/react/blob/master/packages/react/src/ReactHooks.js#L104",
Casi!

Pero aquí están usando un `dispatcher`, que es como un adminstrador de las acciones. 
Por ejemplo, `useEffect` acepta un parámetro `[]` que detecta el cambio del contenido. En dónde podría estar esta lógica?

2020-06-14 00:40 UTC, netpoe commented on src/client.ts
> +                answer: "Respuesta: The code is poetry because through it we shape our desires, feelings,frustrations and emotions, all in order to create something new, something that can build or d
Buena. 
por eso hay que tener cuidado con el AI 😨 🤖

2020-06-14 00:40 UTC, netpoe commented on src/index.ts
> +validateInformation();
Escogiste buenos nombres de las tareas que tiene que realizar el programa 👍

2020-06-14 00:40 UTC, netpoe commented on src/client.ts
> +const data = {
Por favor, coloca este bloque en un `.src/data.json` e importalo para reducir el tamaño de este file y mejorar la organización.

2020-06-14 04:34 UTC, Ktoxcon commented on src/client.ts
> +              "x-password": "qvfWwe3"
Gracias, se me ocurre que una solución podría ser usar variables de entorno.

2020-06-14 04:35 UTC, Ktoxcon commented on src/client.ts
> +                answer: "Respuesta: If I were a senior developer I would like to build something that helps improve everyone's learning in the technological field",
Si, un uso en concreto que se me ocurrió fue enseñar de tecnología a personas mayores o con ningún conocimiento previo.

2020-06-14 04:36 UTC, Ktoxcon commented on src/client.ts
> +                answer: "Respuesta:https://github.com/facebook/react/blob/master/packages/react/src/ReactHooks.js#L104",
Creo que este podría ser:
:https://github.com/facebook/react/blob/655affa302437208e6f03c9ca6d170ea1707ace3/packages/react-reconciler/src/ReactFiberHooks.new.js#L1878"

2020-06-14 04:37 UTC, Ktoxcon commented on src/client.ts
> +                answer: "Respuesta: The code is poetry because through it we shape our desires, feelings,frustrations and emotions, all in order to create something new, something that can build or d
Exactamente!

2020-06-14 04:37 UTC, Ktoxcon commented on src/index.ts
> +validateInformation();
Gracias!

2020-06-14 04:39 UTC, Ktoxcon commented on src/client.ts
> +const data = {
Gracias por la corrección, este y los demás cambios ya fueron hechos 😄

2020-06-14 14:14 UTC, netpoe requested changes
Nuevos comments. 

También, es útil que instales un linter en tu editor. 
Instala esta extensión y disfruta de la magia: https://github.com/prettier/prettier-vscode

2020-06-14 14:14 UTC, netpoe commented on src/client.ts
> +const userPassword = process.env.SERVER_PASSWORD || 'qvfWwe3';
no hay necesidad de poner el fallback

```suggestion
const userPassword = process.env.SERVER_PASSWORD;
```

2020-06-14 14:14 UTC, netpoe commented on file.txt
> +{"contactInfo":{"fullName":"Kenneth Fernando Toxcon Rodas","emailAddress":"ktoxcon@protonmail.com"},"github":{"profileURL":"https://github.com/Ktoxcon","username":"Ktoxcon"},"credentials":{"password"
no hay necesidad de guardar estos `.txt` files.

2020-06-14 14:14 UTC, netpoe commented on key.txt
> +{"contactInfo":{"fullName":"Kenneth Fernando Toxcon Rodas","emailAddress":"ktoxcon@protonmail.com"},"github":{"profileURL":"https://github.com/Ktoxcon","username":"Ktoxcon"},"credentials":{"password"
lo mismo que el comentario anterior. por favor quita estos files del PR

2020-06-14 14:14 UTC, netpoe commented on src/index.ts
> +validateInformation();
No hay necesidad de modificar `src/index.ts`. Por favor, regresa este file al estado original y llama a tus funciones desde `src/client.ts`.

2020-06-14 14:14 UTC, netpoe commented on package.json
> +    "superagent": "^5.2.2",
al parecer no estamos usando esta dependencia. por favor, quítala.

2020-06-14 14:16 UTC, netpoe commented on src/client.ts
> +                answer: "Respuesta: If I were a senior developer I would like to build something that helps improve everyone's learning in the technological field",
con qué objetivo?

2020-06-14 17:37 UTC, Ktoxcon commented on src/client.ts
> +                answer: "Respuesta: If I were a senior developer I would like to build something that helps improve everyone's learning in the technological field",
Con el objetivo de enseñar a más personas como hacer poesía.

2020-06-14 17:39 UTC, Ktoxcon commented on src/client.ts
> +const userPassword = process.env.SERVER_PASSWORD || 'qvfWwe3';
Ya lo corregí y los cambios han sido subidos.

2020-06-14 17:39 UTC, Ktoxcon commented on file.txt
> +{"contactInfo":{"fullName":"Kenneth Fernando Toxcon Rodas","emailAddress":"ktoxcon@protonmail.com"},"github":{"profileURL":"https://github.com/Ktoxcon","username":"Ktoxcon"},"credentials":{"password"
Lo siento, ya los he eliminado.

2020-06-14 17:41 UTC, Ktoxcon commented on src/index.ts
> +validateInformation();
Ya ha sido corregido y los cambios fueron subidos.

2020-06-14 17:42 UTC, Ktoxcon commented on package.json
> +    "superagent": "^5.2.2",
😅 Ya la he borrado.

2020-06-15 01:54 UTC, netpoe requested changes
Los útlimos comentarios y estamos. 

Pudiste instalar `prettier`?

También intenta activar este setting en vscode:

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
```

2020-06-15 01:54 UTC, netpoe commented on src/data.json
> +        "password": "qvfWwe3"
para ocultar esta contraseña, vas a tener que modificar `data` una vez que la importas y antes de enviar el request.

2020-06-15 01:54 UTC, netpoe commented on src/index.ts
> +
Intenta hacer `git checkout master src/index.ts` para regresar este file a como estaba antes.

2020-06-15 03:21 UTC, Ktoxcon commented on src/data.json
> +        "password": "qvfWwe3"
Ya lo he corregido y los cambios han sido subidos.

2020-06-15 03:23 UTC, Ktoxcon commented on src/index.ts
> +
Ya corregí los archivos y subí los cambios a master.

2020-06-15 05:14 UTC, netpoe requested changes
muy cerca!
Si optas por no usar el `await`, entonces quitemos `json-update` del package.json

2020-06-15 05:14 UTC, netpoe commented on src/client.ts
> +  await update(data, { credentials: { password: password } });
Aunque esto funciona, creo que no es necesario hacerlo una promesa, ya que es una llamada síncrona muy veloz y sin hacer un request por el que haya que esperar. 

```suggestion
  data.credentials.password = password; 
```

Si quisieras usar tu método, podría simplificarse así: 

```suggestion
  await update(data, { credentials: { password} });
```

También puedes usar esto: 

```
data = { ...data, credentials: { password } }
```

2020-06-15 07:52 UTC, Ktoxcon commented on src/client.ts
> +  await update(data, { credentials: { password: password } });
Muchas gracias por las observaciones, son de mucha ayuda, creo que yo mismo dificulte las cosas. Ya he corregido esto y los cambios han sido subidos.

2023-02-16 21:30 UTC, closed without merging